/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as PathRouteImport } from './routes/path'
import { Route as PathStageRouteImport } from './routes/path.$stage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const PathStageRoute = PathStageRouteImport.update({
  id: '/$stage',
  path: '/$stage',
  getParentRoute: () => PathRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/path': typeof PathRouteWithChildren
  '/path/$stage': typeof PathStageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/path': typeof PathRouteWithChildren
  '/path/$stage': typeof PathStageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/path': typeof PathRouteWithChildren
  '/path/$stage': typeof PathStageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assess' | '/path' | '/path/$stage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assess' | '/path' | '/path/$stage'
  id: '__root__' | '/' | '/assess' | '/path' | '/path/$stage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  PathRoute: typeof PathRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$stage': {
      id: '/path/$stage'
      path: '/$stage'
      fullPath: '/path/$stage'
      preLoaderRoute: typeof PathStageRouteImport
      parentRoute: typeof PathRoute
    }
  }
}

interface PathRouteChildren {
  PathStageRoute: typeof PathStageRoute
}

const PathRouteChildren: PathRouteChildren = {
  PathStageRoute: PathStageRoute,
}

const PathRouteWithChildren = PathRoute._addFileChildren(PathRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  PathRoute: PathRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
