/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as CaseSubmitRouteImport } from './routes/case-submit'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as MedalsRouteImport } from './routes/medals'
import { Route as BasesIndexRouteImport } from './routes/bases.index'
import { Route as BasesBaseIdRouteImport } from './routes/bases.$baseId'
import { Route as CirclesIndexRouteImport } from './routes/circles.index'
import { Route as CirclesCircleIdRouteImport } from './routes/circles.$circleId'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as PathIndexRouteImport } from './routes/path.index'
import { Route as PathStageRouteImport } from './routes/path.$stage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSubmitRoute = CaseSubmitRouteImport.update({
  id: '/case-submit',
  path: '/case-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const MedalsRoute = MedalsRouteImport.update({
  id: '/medals',
  path: '/medals',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesIndexRoute = BasesIndexRouteImport.update({
  id: '/bases/',
  path: '/bases/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesBaseIdRoute = BasesBaseIdRouteImport.update({
  id: '/bases/$baseId',
  path: '/bases/$baseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesCircleIdRoute = CirclesCircleIdRouteImport.update({
  id: '/circles/$circleId',
  path: '/circles/$circleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PathIndexRoute = PathIndexRouteImport.update({
  id: '/path/',
  path: '/path/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathStageRoute = PathStageRouteImport.update({
  id: '/path/$stage',
  path: '/path/$stage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/case-submit': typeof CaseSubmitRoute
  '/enroll': typeof EnrollRoute
  '/medals': typeof MedalsRoute
  '/bases/$baseId': typeof BasesBaseIdRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/path/$stage': typeof PathStageRoute
  '/bases/': typeof BasesIndexRoute
  '/circles/': typeof CirclesIndexRoute
  '/path/': typeof PathIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/case-submit': typeof CaseSubmitRoute
  '/enroll': typeof EnrollRoute
  '/medals': typeof MedalsRoute
  '/bases/$baseId': typeof BasesBaseIdRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/path/$stage': typeof PathStageRoute
  '/bases': typeof BasesIndexRoute
  '/circles': typeof CirclesIndexRoute
  '/path': typeof PathIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/case-submit': typeof CaseSubmitRoute
  '/enroll': typeof EnrollRoute
  '/medals': typeof MedalsRoute
  '/bases/$baseId': typeof BasesBaseIdRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/path/$stage': typeof PathStageRoute
  '/bases/': typeof BasesIndexRoute
  '/circles/': typeof CirclesIndexRoute
  '/path/': typeof PathIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assess'
    | '/case-submit'
    | '/enroll'
    | '/medals'
    | '/bases/$baseId'
    | '/circles/$circleId'
    | '/course/$courseId'
    | '/path/$stage'
    | '/bases/'
    | '/circles/'
    | '/path/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assess'
    | '/case-submit'
    | '/enroll'
    | '/medals'
    | '/bases/$baseId'
    | '/circles/$circleId'
    | '/course/$courseId'
    | '/path/$stage'
    | '/bases'
    | '/circles'
    | '/path'
  id:
    | '__root__'
    | '/'
    | '/assess'
    | '/case-submit'
    | '/enroll'
    | '/medals'
    | '/bases/$baseId'
    | '/circles/$circleId'
    | '/course/$courseId'
    | '/path/$stage'
    | '/bases/'
    | '/circles/'
    | '/path/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  CaseSubmitRoute: typeof CaseSubmitRoute
  EnrollRoute: typeof EnrollRoute
  MedalsRoute: typeof MedalsRoute
  BasesBaseIdRoute: typeof BasesBaseIdRoute
  CirclesCircleIdRoute: typeof CirclesCircleIdRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  PathStageRoute: typeof PathStageRoute
  BasesIndexRoute: typeof BasesIndexRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
  PathIndexRoute: typeof PathIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-submit': {
      id: '/case-submit'
      path: '/case-submit'
      fullPath: '/case-submit'
      preLoaderRoute: typeof CaseSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medals': {
      id: '/medals'
      path: '/medals'
      fullPath: '/medals'
      preLoaderRoute: typeof MedalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases/': {
      id: '/bases/'
      path: '/bases'
      fullPath: '/bases/'
      preLoaderRoute: typeof BasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases/$baseId': {
      id: '/bases/$baseId'
      path: '/bases/$baseId'
      fullPath: '/bases/$baseId'
      preLoaderRoute: typeof BasesBaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/': {
      id: '/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$circleId': {
      id: '/circles/$circleId'
      path: '/circles/$circleId'
      fullPath: '/circles/$circleId'
      preLoaderRoute: typeof CirclesCircleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/': {
      id: '/path/'
      path: '/path'
      fullPath: '/path/'
      preLoaderRoute: typeof PathIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$stage': {
      id: '/path/$stage'
      path: '/path/$stage'
      fullPath: '/path/$stage'
      preLoaderRoute: typeof PathStageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  CaseSubmitRoute: CaseSubmitRoute,
  EnrollRoute: EnrollRoute,
  MedalsRoute: MedalsRoute,
  BasesBaseIdRoute: BasesBaseIdRoute,
  CirclesCircleIdRoute: CirclesCircleIdRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  PathStageRoute: PathStageRoute,
  BasesIndexRoute: BasesIndexRoute,
  CirclesIndexRoute: CirclesIndexRoute,
  PathIndexRoute: PathIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
